language: node_js
node_js:
    - "8.1.2"
env:
    global:
        - NODE_ENV=test
addons:
    apt:
      packages:
        - xvfb
install:
    - mysql -uroot -e "create database tacowasa"
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
    - npm i
    - npm run migrate:test
    - npm run build
    - npm run lint:all
    - npm run test:cover
after_success:
    - npm run coveralls
