language: node_js
node_js:
    - "6.3.1"
env:
    global:
        - NODE_ENV=test
install:
    - mysql -uroot -e "create database tacowasa_test"
before_script:
script:
    - npm run migrate:test
    - npm run test:cover
after_success:
    - npm run coveralls